import pytest
import json
import os
import tempfile

from server.services.transcript_watcher import TranscriptHandler


class TestTranscriptCommandFilter:
    """Tests that slash command XML noise is filtered from transcript output."""

    def _make_handler(self):
        handler = TranscriptHandler(
            content_callback=None,
            audio_callback=None,
            loop=None,
            server=type('FakeServer', (), {'active_session_id': 'test', 'current_branch': ''})(),
            user_callback=None,
        )
        return handler

    def test_filters_local_command_caveat(self):
        """Lines with <local-command-caveat> should be skipped."""
        handler = self._make_handler()

        with tempfile.NamedTemporaryFile(mode='w', suffix='.jsonl', delete=False) as f:
            entry = {
                "message": {
                    "role": "user",
                    "content": '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>'
                }
            }
            f.write(json.dumps(entry) + '\n')
            f.flush()

            handler.expected_session_file = f.name
            blocks, user_texts, task_ids = handler.extract_new_content(f.name)

        os.unlink(f.name)
        assert user_texts == []

    def test_filters_command_name(self):
        """Lines with <command-name> should be skipped."""
        handler = self._make_handler()

        with tempfile.NamedTemporaryFile(mode='w', suffix='.jsonl', delete=False) as f:
            entry = {
                "message": {
                    "role": "user",
                    "content": '<command-name>/effort</command-name>\n<command-message>effort</command-message>'
                }
            }
            f.write(json.dumps(entry) + '\n')
            f.flush()

            blocks, user_texts, task_ids = handler.extract_new_content(f.name)

        os.unlink(f.name)
        assert user_texts == []

    def test_filters_local_command_stdout(self):
        """Lines with <local-command-stdout> should be skipped."""
        handler = self._make_handler()

        with tempfile.NamedTemporaryFile(mode='w', suffix='.jsonl', delete=False) as f:
            entry = {
                "message": {
                    "role": "user",
                    "content": '<local-command-stdout>Effort level: auto (currently medium)</local-command-stdout>'
                }
            }
            f.write(json.dumps(entry) + '\n')
            f.flush()

            blocks, user_texts, task_ids = handler.extract_new_content(f.name)

        os.unlink(f.name)
        assert user_texts == []

    def test_passes_normal_user_message(self):
        """Normal user messages should NOT be filtered."""
        handler = self._make_handler()

        with tempfile.NamedTemporaryFile(mode='w', suffix='.jsonl', delete=False) as f:
            entry = {
                "message": {
                    "role": "user",
                    "content": "fix the bug in server.py"
                }
            }
            f.write(json.dumps(entry) + '\n')
            f.flush()

            blocks, user_texts, task_ids = handler.extract_new_content(f.name)

        os.unlink(f.name)
        assert len(user_texts) == 1
        assert user_texts[0][0] == "fix the bug in server.py"

    def test_passes_compact_summary(self):
        """/compact summary (plain text, no XML tags) should NOT be filtered."""
        handler = self._make_handler()

        with tempfile.NamedTemporaryFile(mode='w', suffix='.jsonl', delete=False) as f:
            entry = {
                "message": {
                    "role": "user",
                    "content": "This session is being continued from a previous conversation..."
                }
            }
            f.write(json.dumps(entry) + '\n')
            f.flush()

            blocks, user_texts, task_ids = handler.extract_new_content(f.name)

        os.unlink(f.name)
        assert len(user_texts) == 1

    def test_filters_content_list_with_command_caveat(self):
        """Content as list with <local-command-caveat> in text block should be filtered."""
        handler = self._make_handler()

        with tempfile.NamedTemporaryFile(mode='w', suffix='.jsonl', delete=False) as f:
            entry = {
                "message": {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": "<local-command-caveat>Caveat: ...</local-command-caveat>"}
                    ]
                }
            }
            f.write(json.dumps(entry) + '\n')
            f.flush()

            blocks, user_texts, task_ids = handler.extract_new_content(f.name)

        os.unlink(f.name)
        assert user_texts == []
